### ISSUE TITLE
Maybe there is a bug in gcommand_loader.py

### ISSUE THREAD

**Issue by lijianhackthon** [adiyoss/GCommandsPytorch#2]
Thanks for sharing your code. Now I am using your pre-processing code for my own corpus. When I watch the code, I have found that there maybe a bug in the 64th line in gcommand_loader.py. In my opinion, it should be "spect = spect[:, :max_len]" rather than "spect = spect[:max_len, ]". Correct me if I am wrong, Thanks.

**Comment by adiyoss** [comment]
Hi,
You are right! I fixed it
Thanks :)
